---
- include_vars: file=common_vars.yml
- name: Set remote MySQL user
  mysql_user: 
    name: "{{ item.user }}"
    password: "{{ item.password }}"
    host: "{{ item.host }}"
    priv: "{{ item.priv }}"
    state: present
  with_items: 
    - "{{ mysql_users}}"
  when: mysql_users is defined
