- include_vars: file=common_vars.yml
- name: Verify hosts file
  lineinfile:
    dest: /etc/hosts
    line: "{{ item.l }}"
  with_items: "{{ hosts_file }}"

- set_fact: enable_fastestmirror_plugin=0

- name: Disable YUM fastestmirror plugin
  template:
    src: fastestmirror.conf.j2
    dest: /etc/yum/pluginconf.d/fastestmirror.conf

- name: Install base programs
  yum: name={{item}} state=present enablerepo=epel
  with_items:
  - htop
  - telnet
  - wget
  - vim
  - nmap
  - python-pip

